blank_issues_enabled: false
contact_links:
  - name: "Discussões"
    url: "https://github.com/FabioCarlesso/prompt-finction/discussions"
    about: "Use as discussões para perguntas gerais e ideias."
